# SPDX-License-Identifier: LGPL-2.1-only
# Offline arithmetic encoder. The generated bytes must pass independent 7z.
# Model order follows libmspack qtmd.c (Stuart Caie / Matthew Russotto).
from pathlib import Path
import struct


class Model:
    def __init__(self, start, n):
        self.a = [[start + i, n - i] for i in range(n + 1)]
        self.shifts = 4

    def update(self, i):
        for x in self.a[: i + 1]:
            x[1] += 8
        if self.a[0][1] <= 3800:
            return
        self.shifts -= 1
        n = len(self.a) - 1
        if self.shifts:
            for i in range(n - 1, -1, -1):
                self.a[i][1] = max(self.a[i][1] // 2, self.a[i + 1][1] + 1)
        else:
            self.shifts = 50
            for i in range(n):
                self.a[i][1] = (self.a[i][1] - self.a[i + 1][1] + 1) // 2
            for i in range(n - 1):
                for j in range(i + 1, n):
                    if self.a[i][1] < self.a[j][1]:
                        self.a[i], self.a[j] = self.a[j], self.a[i]
            for i in range(n - 1, -1, -1):
                self.a[i][1] += self.a[i + 1][1]


class Encoder:
    def __init__(self, order):
        n = 2 * order
        self.models = [
            Model(0, 64),
            Model(64, 64),
            Model(128, 64),
            Model(192, 64),
            Model(0, min(n, 24)),
            Model(0, min(n, 36)),
            Model(0, n),
            Model(0, 27),
            Model(0, 7),
        ]
        self.history = bytearray()
        self.order = order

    def symbol(self, model, value):
        m = self.models[model]
        i = next(i for i, s in enumerate(m.a[:-1]) if s[0] == value)
        span = self.h - self.l + 1
        total = m.a[0][1]
        self.h = self.l + span * m.a[i][1] // total - 1
        self.l += span * m.a[i + 1][1] // total
        m.update(i)
        while True:
            if self.h < 32768:
                self.emit(0)
            elif self.l >= 32768:
                self.emit(1)
                self.l -= 32768
                self.h -= 32768
            elif self.l >= 16384 and self.h < 49152:
                self.pending += 1
                self.l -= 16384
                self.h -= 16384
            else:
                break
            self.l *= 2
            self.h = self.h * 2 + 1
            self.shifts += 1

    def emit(self, bit):
        self.bits.append(bit)
        self.bits.extend([1 - bit] * self.pending)
        self.pending = 0

    def raw(self, value, n):
        # Decoder read-ahead is 16 coded bits. Record raw fields at their
        # arithmetic-consumption position, then interleave them after the
        # encoder resolves pending underflow bits. Directly appending raw
        # bits during symbol encoding would place them too early.
        if n:
            self.raws.append(
                (16 + self.shifts, [(value >> i) & 1 for i in range(n - 1, -1, -1)])
            )

    def literal(self, b):
        self.symbol(8, b // 64)
        self.symbol(b // 64, b)
        self.history.append(b)

    def match(self, selector, slot, lengthslot=0, extra=0):
        self.symbol(8, selector)
        if selector == 6:
            self.symbol(7, lengthslot)
            le = 0 if lengthslot == 26 else max(0, lengthslot - 2) // 4
            lb = (
                254
                if lengthslot == 26
                else sum(1 << (max(0, i - 2) // 4) for i in range(lengthslot))
            )
            self.raw(extra, le)
            length = lb + extra + 5
        else:
            length = selector - 1
        self.symbol(selector, slot)
        pe = max(0, slot - 2) // 2
        pb = slot if slot < 4 else (2 | (slot & 1)) << pe
        value = (1 << pe) - 1 if pe else 0
        self.raw(value, pe)
        distance = pb + value + 1
        assert distance <= min(len(self.history), 1 << self.order)
        for _ in range(length):
            self.history.append(self.history[-distance])

    def frame(self, second=False, full=False, far=False):
        self.l = 0
        self.h = 65535
        self.pending = 0
        self.shifts = 0
        self.bits = []
        self.raws = []
        start = len(self.history)
        if second:
            if full:
                while len(self.history) - start <= 32768 - 266:
                    self.match(4, min(23, 2 * self.order - 1) if far else 19)
                    self.match(5, min(35, 2 * self.order - 1) if far else 19)
                    self.match(6, 2 * self.order - 1 if far else 19, 26)
            else:
                for i in range(80):
                    self.match(6, min(19, 2 * self.order - 1), 26)
        else:
            for i in range(2048):
                self.literal((i * 73 + i // 17) % 256)
            for repetition in range(10):
                for slot in range(min(20, 2 * self.order)):
                    self.match(4, slot)
                    self.match(5, slot)
                for ls in range(27):
                    self.match(
                        6,
                        min(19, 2 * self.order - 1),
                        ls,
                        (1 << (max(0, ls - 2) // 4)) - 1 if ls < 26 else 0,
                    )
        size = 32768 if not second or full else len(self.history) - start + 19
        while len(self.history) - start < size:
            self.literal((len(self.history) * 127 + len(self.history) // 251) % 256)
        assert len(self.history) - start == size
        self.pending += 1
        self.emit(0 if self.l < 16384 else 1)
        while len(self.bits) < 16 + self.shifts + 2:
            self.bits.append(0)
        bits = []
        last = 0
        for position, raw in self.raws:
            bits.extend(self.bits[last:position])
            bits.extend(raw)
            last = position
        bits.extend(self.bits[last:])
        bits.extend([0] * ((-len(bits)) % 8))
        return bytes(
            sum(bits[i + j] << (7 - j) for j in range(8))
            for i in range(0, len(bits), 8)
        ), bytes(self.history[start:])


def cabinet(order, frames):
    prefix = sum(len(data) for _, data in frames[:-1])
    names = [("first.bin", 0, prefix), ("later.bin", prefix, len(frames[-1][1]))]
    b = bytearray(44)
    b[:4] = b"MSCF"
    b[24:26] = b"\x03\x01"
    struct.pack_into("<I", b, 16, 44)
    struct.pack_into("<HH", b, 26, 1, len(names))
    struct.pack_into("<HH", b, 40, len(frames), (order << 8) | 0x72)
    for name, offset, size in names:
        b.extend(struct.pack("<IIHHHH", size, offset, 0, 0, 0, 0))
        b.extend(name.encode() + b"\0")
    struct.pack_into("<I", b, 36, len(b))
    for comp, data in frames:
        b.extend(struct.pack("<IHH", 0, len(comp), len(data)))
        b.extend(comp)
    struct.pack_into("<I", b, 8, len(b))
    return b


import argparse

parser = argparse.ArgumentParser(description="Generate CAB Quantum validation fixtures")
parser.add_argument("--output", type=Path, required=True)
out = parser.parse_args().output
out.mkdir(parents=True, exist_ok=False)
for order in range(10, 22):
    enc = Encoder(order)
    frames = [enc.frame(), enc.frame(True)]
    (out / f"quantum-{order}.cab").write_bytes(cabinet(order, frames))
    for name, (_, data) in zip(["first.bin", "later.bin"], frames):
        (out / f"quantum-{order}-{name}").write_bytes(data)
    print(order, [(len(c), len(d)) for c, d in frames])

# Four MiB of history exercises the highest offset slots and all position
# model reorder cycles; arithmetic state restarts for every 32 KiB frame.
enc = Encoder(21)
frames = [enc.frame()]
for index in range(1, 128):
    frames.append(enc.frame(True, full=True, far=index >= 64))
(out / "quantum-high-history.cab").write_bytes(cabinet(21, frames))
(out / "quantum-high-history-first.bin").write_bytes(
    b"".join(data for _, data in frames[:-1])
)
(out / "quantum-high-history-later.bin").write_bytes(frames[-1][1])

# A root package manifest checks default inventory integration. Literal coding
# avoids depending on the Rust package parser or decoder to generate the input.
xml = (
    b'<assembly xmlns="urn:schemas-microsoft-com:asm.v3" manifestVersion="1.0">'
    b'<assemblyIdentity name="Synthetic.Quantum.Package" version="10.0.19041.1" '
    b'processorArchitecture="amd64" language="neutral" publicKeyToken="31bf3856ad364e35"/>'
    b'<package identifier="Synthetic" releaseType="Feature Pack"/></assembly>'
)
enc = Encoder(18)
enc.l = 0
enc.h = 65535
enc.pending = 0
enc.shifts = 0
enc.bits = []
enc.raws = []
for byte in xml:
    enc.literal(byte)
enc.pending += 1
enc.emit(0 if enc.l < 16384 else 1)
while len(enc.bits) < 16 + enc.shifts + 2:
    enc.bits.append(0)
enc.bits.extend([0] * ((-len(enc.bits)) % 8))
encoded = bytes(
    sum(enc.bits[i + j] << (7 - j) for j in range(8))
    for i in range(0, len(enc.bits), 8)
)
b = bytearray(44)
b[:4] = b"MSCF"
b[24:26] = b"\x03\x01"
struct.pack_into("<IHH", b, 16, 44, 0, 0)
struct.pack_into("<HH", b, 26, 1, 1)
struct.pack_into("<HH", b, 40, 1, 0x1272)
b.extend(struct.pack("<IIHHHH", len(xml), 0, 0, 0, 0, 0))
b.extend(b"update.mum\0")
struct.pack_into("<I", b, 36, len(b))
b.extend(struct.pack("<IHH", 0, len(encoded), len(xml)))
b.extend(encoded)
struct.pack_into("<I", b, 8, len(b))
(out / "quantum-package.cab").write_bytes(b)
(out / "quantum-package-update.mum").write_bytes(xml)
